apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Test11
  description: TestOrgMy
  annotations:
    github.com/project-slug: TestOrgMy/test11
    backstage.io/techdocs-ref: github:https://github.com/TestOrgMy/test11
spec:
  type: website
  lifecycle: experimental
  owner: TestOrgMy
