---
name: tests

on:
  pull_request:
    branches: [ master ]

jobs:
  conformance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git fetch origin +refs/heads/master:refs/heads/master

      # for pre-commit
      - uses: actions/setup-python@v1
      - name: set PY
        run: echo "::set-env name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - uses: pre-commit/action@v1.0.1
        with:
          token: ${{ secrets.github_token }}

  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          go mod vendor
      - name: Run tests
        run: |
          go test -v -covermode=count -coverprofile=coverage.out ./...
      - name: Convert Go coverage to LCOV
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Send code coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: ./coverage.lcov
          flag-name: unit
